## Peptide quantification accuracy plots for DIA vs HRMS1-DIA (OT and LIT)

### Data and packages 

```{r}
library(tidyverse)
library(ggprism)
library(ggridges)
```

```{r}
#Reading the LongReportV2 tables from SN16

dia_ot <- read.csv("data/DIA-R6-Re-120k-30k-15mz-40w.csv", sep = ";", dec = ",") %>% mutate(method = "DIA-OT")
hrms1_ot <- read.csv("data/DIA-R6-Re-120k-60k-8mz-75w.csv", sep = ";", dec = ",") %>% mutate(method = "HRMS1-OT")
dia_lit <- read.csv("data/DIA-R6-Re-120k-Normal-10mz-40w.csv", sep = ";", dec = ",") %>% mutate(method = "DIA-LIT")
hrms1_lit <- read.csv("data/DIA-R6-Re-120k-Normal-5mz-120w.csv", sep = ";", dec = ",") %>% mutate(method = "HRMS1-LIT")

```

#### Colors 
```{r}
myColors2 = c("#5f0f40", '#9a031e', '#fb8b24', '#e36414', '#0f4c5c')
myColors = c("#355070", '#6d597a', '#b56576', '#e56b6f', '#eaac8b')
```

### Data points per peak plots 
```{r}
#Points per peak plots 

ppp <- bind_rows(list(dia_ot    %>% select(R.Replicate, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', method),
                      hrms1_ot  %>% select(R.Replicate, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', method),
                      dia_lit   %>% select(R.Replicate, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', method),
                      hrms1_lit %>% select(R.Replicate, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', method)

))

colnames(ppp) <- c("Rep", "MS2", "MS1", "Method")
```

```{r}
#Plotting points per peak for OT-OT based DIA, change "OT" -> "LIT" for LIT-DIA figures

ggplot(ppp %>% filter(Rep == 3, grepl("OT", Method)), aes(x = MS1, fill = Method, color = Method)) + 
        geom_histogram(aes(y = ..density..), binwidth = 1, alpha =0.7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(rows=vars(Method)) + 
        geom_vline(xintercept = 3, linetype ="dashed", size = 0.7, color = "grey") + 
        scale_fill_manual(values = myColors2[c(3,5)]) + 
        scale_color_manual(values = myColors2[c(3,5)]) +
        theme_prism() +
        theme(legend.position = "none") +
        xlim(c(0,20)) +
        xlab('MS1 Datapoints per peak') + ylab("Density")

ggplot(ppp %>% filter(Rep == 3, grepl("OT", Method)), aes(x = MS2, fill = Method, color = Method)) + 
        geom_histogram(aes(y = ..density..), binwidth = 1, alpha =0.7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(rows=vars(Method)) + 
        geom_vline(xintercept = 3, linetype ="dashed", size = 0.7, color = "grey") + 
        scale_fill_manual(values = myColors2[c(3,5)]) + 
        scale_color_manual(values = myColors2[c(3,5)]) +
        theme_prism() +
        theme(legend.position = "none") +
        xlim(c(0,25)) +
        xlab('MS2 Datapoints per peak') + ylab("Density")

```

### Precision plots 
```{r}
prec_pg <- bind_rows(list(dia_ot    %>% select(PG.ProteinAccessions, PG.MS1Quantity, PG.MS2Quantity, method) %>% distinct(),
                      hrms1_ot  %>% select(PG.ProteinAccessions, PG.MS1Quantity, PG.MS2Quantity, method)%>% distinct(),
                      dia_lit   %>% select(PG.ProteinAccessions, PG.MS1Quantity, PG.MS2Quantity, method)%>% distinct(),
                      hrms1_lit %>% select(PG.ProteinAccessions, PG.MS1Quantity, PG.MS2Quantity, method) %>% distinct()
                      )) %>% 
                      group_by(method, PG.ProteinAccessions) %>% 
                      summarise(std_ms1 = sd(PG.MS1Quantity), std_ms2 = sd(PG.MS2Quantity),
                                abundance_ms1 = mean(PG.MS1Quantity), abundance_ms2 = mean(PG.MS2Quantity),
                                cv_ms1 = std_ms1/abundance_ms1, cv_ms2 = std_ms2/abundance_ms2) %>% na.omit() 

#Get list of common detected peptides in the methods 
detected_in_all <- Reduce(intersect, list(dia_ot$PG.ProteinAccessions,
                                          hrms1_ot$PG.ProteinAccessions,
                                          dia_lit$PG.ProteinAccessions,
                                          hrms1_lit$PG.ProteinAccessions))

detected_in_ot <- intersect(dia_ot$PG.ProteinAccessions, hrms1_ot$PG.ProteinAccessions)
detected_in_lit <- intersect(dia_lit$PG.ProteinAccessions, hrms1_lit$PG.ProteinAccessions)
```

```{r}
#Compare MS2 quant for DIA and MS1 quant for HRMS1 making a new column for that 
prec_pg <- prec_pg %>%
        mutate(comp_quant = case_when(grepl("HRMS1", method) ~ cv_ms1, 
                                      grepl("DIA-OT", method) ~ cv_ms2,
                                      grepl("DIA-LIT", method) ~ cv_ms2))

ggplot(prec_pg %>% filter(PG.ProteinAccessions %in% detected_in_ot, grepl("OT", method)), 
        aes(x = comp_quant, color = method, fill = method)) + 
        geom_histogram(aes(y=..density..),bins = 50, alpha = .7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(rows = vars(method)) + 
        theme_prism() +
        scale_fill_manual(values = myColors2) + 
        scale_color_manual(values = myColors2) +
        theme_prism() +
        theme(legend.position = "none") +
        xlab('CV') + ylab("Density") +
        xlim(c(0,0.3)) +
        ggtitle("OT")

ggplot(prec_pg %>% filter(PG.ProteinAccessions %in% detected_in_ot, grepl("LIT", method)), 
        aes(x = comp_quant, color = method, fill = method)) + 
        geom_histogram(aes(y=..density..),bins = 50, alpha = .7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(rows = vars(method)) + 
        theme_prism() +
        scale_fill_manual(values = myColors2[c(3,5)]) + 
        scale_color_manual(values = myColors2[c(3,5)]) +
        theme_prism() +
        theme(legend.position = "none") +
        xlab('CV') + ylab("Density") +
        xlim(c(0,0.3)) +
        ggtitle("LIT")
```

### Some extra plots 
```{r}
# CV hexbins plots 
ggplot(prec_pg %>% filter(PG.ProteinAccessions %in% detected_in_ot, grepl("LIT", method)),
        aes(x = comp_quant, y= log2(abundance_ms1))) +
        geom_hex(bins=35) +
        xlim(c(0,0.3)) +
        facet_wrap(~method) +
        theme_prism() +
        viridis::scale_fill_viridis(option = "G") +
        ylab("log2(Abundance)") + xlab("CV")

ggplot(prec_pg %>% filter(PG.ProteinAccessions %in% detected_in_ot, grepl("OT", method)),
        aes(x = comp_quant, y= log2(abundance_ms1))) +
        geom_hex(bins=35) +
        xlim(c(0,0.3)) +
        facet_wrap(~method) +
        theme_prism() +
        viridis::scale_fill_viridis(option = "F") +
        ylab("log2(Abundance)") + xlab("CV")
```

### Protein rankplots 

```{r}
pg <- bind_rows(list(dia_ot    %>% select(R.Replicate,PG.ProteinAccessions, PG.MS1Quantity, method),
                      hrms1_ot  %>% select(R.Replicate,PG.ProteinAccessions, PG.MS1Quantity, method)) ) %>% distinct()
                      
ranks <-  pg %>%  group_by(PG.ProteinAccessions) %>% 
                    summarise(expr = log2(mean(PG.MS1Quantity, na.rm = TRUE))) %>% 
                    mutate(prot_rank = rank(expr))%>% distinct()

rank_pg <- left_join(pg %>% select(method, PG.ProteinAccessions) %>% distinct(), ranks, by = "PG.ProteinAccessions")
```

```{r}
ggplot(rank_pg %>% filter(grepl("OT", method)), 
        aes(x = prot_rank, y = expr, color = method)) +
        geom_point(alpha = 0.02) + 
        facet_wrap(~method, ncol = 1) +
        theme_prism() +
        scale_fill_manual(values = myColors2) + 
        scale_color_manual(values = myColors2) +
        theme_prism() +
        theme(legend.position = "none") +
        xlab('Rank') + ylab("log2(Abundance)") +
        geom_vline(xintercept = 1000, linetype ="dashed", size = 0.7, color = "grey") 

```


```{r}
ggplot(rank_pg %>% filter(grepl("OT", method)), 
        aes(x = prot_rank, color = method, fill = method)) +
        geom_histogram(bins = 30, alpha = .7) +
        facet_wrap(~method, ncol = 1) +
        theme_prism() +
        scale_fill_manual(values = myColors2) + 
        scale_color_manual(values = myColors2) +
        theme_prism() +
        theme(legend.position = "none") +
        xlab('Rank') + ylab("Detected proteins") 
```