# Analysis of Hela heavy and light mix for accuracy estimation 

#### Packages
```{r}
library(tidyverse)
library(ggprism)
library(ggridges)
library(viridis)

myColors2 = c("#5f0f40", '#9a031e', '#fb8b24', '#e36414', '#0f4c5c')
myColors = c("#355070", '#6d597a', '#b56576', '#e56b6f', '#eaac8b')
```

#### Data
```{r}
#Reading data in a bad way 
ng1_11 <- read.csv('data/SILAC/R12-1ng-11-Lib12_SILAC.txt', sep = "\t", dec = ",") %>% as_tibble()
ng1_12 <- read.csv('data/SILAC/R12-1ng-12-Lib_SILAC.txt', sep = "\t", dec = ",") %>% as_tibble()
ng1_13 <- read.csv('data/SILAC/R12-1ng-13-Lib_SILAC.txt', sep = "\t", dec = ",") %>% as_tibble()
ng1_14 <- read.csv('data/SILAC/R12-1ng-14-Lib_SILAC.txt', sep = "\t", dec = ",") %>% as_tibble()
ng1_15 <- read.csv('data/SILAC/R12-1ng-15-Lib_SILAC.txt', sep = "\t", dec = ",") %>% as_tibble()
```

## Rename columns 
```{r}
#Function for quickly changing the columns of all the files 
renameColumns1ng <- function(df){
    temp <- df
    method <- str_match(colnames(temp), pattern = "40SPD_(.+?)_SILAC")[,2]
    mix <- str_match(colnames(temp), pattern = "SILAC_(.+?)_1ng")[,2]
    quant <- str_match(colnames(temp), pattern = "MS.Channel.*")
    replicate <- str_match(colnames(temp), pattern = "1ng_(.)")[,2]

    new_colnames <- c("Accessions", paste(paste(paste(method,mix, sep = "."), quant, sep = "."), replicate, sep = ".")[2:25])
    colnames(temp) <- new_colnames
    temp
    }

renameColumns10ng <- function(df){
    temp <- df
    method <- str_match(colnames(temp), pattern = "40SPD_(.+?)_SILAC")[,2]
    mix <- str_match(colnames(temp), pattern = "SILAC_(.+?)_10ng")[,2]
    quant <- str_match(colnames(temp), pattern = "MS.Channel.*")
    replicate <- str_match(colnames(temp), pattern = "10ng_(.)")[,2]

    new_colnames <- c("Accessions", paste(paste(paste(method,mix, sep = "."), quant, sep = "."), replicate, sep = ".")[2:25])
    colnames(temp) <- new_colnames
    temp
    }
#Applying the functions 

#1ng 
ng1_11 <- renameColumns1ng(ng1_11)
ng1_12 <- renameColumns1ng(ng1_12)
ng1_13 <- renameColumns1ng(ng1_13)
ng1_14 <- renameColumns1ng(ng1_14)
ng1_15 <- renameColumns1ng(ng1_15)


```
## Extract MS1 info
```{r}
#Extracts the MS1 quant information and converts it into long format for plotting and further analysis
extractMS1 <- function(df){
    #df - dataframe from the renameColumns function
    #Separate MS1 and MS2 based quant 
    prot_ms1 <- df[grepl("Accessions|MS1Channel", colnames(df))]
    #Convert to long format
    prot_ms1 <- prot_ms1 %>% gather(Run, Abundance, -Accessions) %>% 
            separate(Run, c("Method", "Mix", "Quant", "Replicate"), sep = "\\.") %>% 
            group_by(Method,Mix, Quant) %>% filter(!(Abundance %in% c("1", "Filtered", "NaN"))) %>% 
            mutate(Abundance = as.numeric(gsub(",", "\\.", Abundance)))
    prot_ms1
    }

#Extracts the MS1 quant information and converts it into long format for plotting and further analysis
extractMS2 <- function(df){
    #df - dataframe from the renameColumns function
    #Separate MS1 and MS2 based quant 
    prot_ms1 <- df[grepl("Accessions|MS2Channel", colnames(df))]
    #Convert to long format
    prot_ms1 <- prot_ms1 %>% gather(Run, Abundance, -Accessions) %>% 
            separate(Run, c("Method", "Mix", "Quant", "Replicate"), sep = "\\.") %>% 
            group_by(Method,Mix, Quant) %>% filter(!(Abundance %in% c("1", "Filtered", "NaN"))) %>% 
            mutate(Abundance = as.numeric(gsub(",", "\\.", Abundance)))
    prot_ms1
    }

ng1_11_ms1 <- extractMS1(ng1_11)
ng1_12_ms1 <- extractMS1(ng1_12)
ng1_13_ms1 <- extractMS1(ng1_13)
ng1_14_ms1 <- extractMS1(ng1_14)
ng1_15_ms1 <- extractMS1(ng1_15)

ng1_11_ms2 <- extractMS2(ng1_11)
ng1_12_ms2 <- extractMS2(ng1_12)
ng1_13_ms2 <- extractMS2(ng1_13)
ng1_14_ms2 <- extractMS2(ng1_14)
ng1_15_ms2 <- extractMS2(ng1_15)

ng1_ms1 <- bind_rows(list(ng1_11_ms1, ng1_12_ms1, ng1_13_ms1, ng1_14_ms1, ng1_15_ms1))
ng1_ms2 <- bind_rows(list(ng1_11_ms2,ng1_12_ms2, ng1_13_ms2, ng1_14_ms2, ng1_15_ms2))
```


## Calculate logFC and CV (not used)
```{r}
#Calculating the logFC in values 
calculateStatsMS1 <- function(df){
    prot_ms1 <- df
    prot_means <- prot_ms1 %>% group_by(Accessions, Method, Mix, Quant) %>% 
        summarise(avg = log2(mean(Abundance)))

    #prot_cv <- prot_ms1 %>% group_by(Accessions, Method, Mix, Quant) %>% 
    #    summarise(cv = sd(Abundance)/mean(Abundance))

    prot_FC_ms1 <- prot_means %>% spread(Quant, avg) %>% mutate(logFC = MS1Channel2 - MS1Channel1) %>% 
                mutate(Mix = gsub("_", ":", Mix))
    
    prot_FC_ms1
}

calculateStatsMS2 <- function(df){
    prot_ms2 <- df
    prot_means <- prot_ms2 %>% group_by(Accessions, Method, Mix, Quant) %>% 
        summarise(avg = log2(mean(Abundance)))

    #prot_cv <- prot_ms1 %>% group_by(Accessions, Method, Mix, Quant) %>% 
    #    summarise(cv = sd(Abundance)/mean(Abundance))

    prot_FC_ms2 <- prot_means %>% spread(Quant, avg) %>% mutate(logFC = MS2Channel2 - MS2Channel1) %>% 
                mutate(Mix = gsub("_", ":", Mix))
    
    prot_FC_ms2
}

#1ng 
ng1_fc_ms1 <- calculateStatsMS1(ng1_ms1) %>% mutate(Load = "1ng", Quant = "MS1")
ng1_fc_ms2 <- calculateStatsMS2(ng1_ms2) %>% mutate(Load = "1ng", Quant = "MS2")

```

### Calculate summaries to be added to the plots 
```{r}
ng1_labels <- bind_rows(ng1_fc_ms1,ng1_fc_ms2) %>% group_by(Method, Mix, Quant) %>% 
    summarise(mu = mean(logFC, na.rm = TRUE), std = sd(logFC, na.rm =TRUE)) 
```

### Leave only the proteins detected 
```{r}
#Filter for only proteins that are detected in all runs 

#Filter proteins that are detected in both methods 
ng1 <- bind_rows(list(ng1_11, ng1_12, ng1_13, ng1_14, ng1_15))

```

#### Detection in method
```{r}
ggplot(ng1_fc_ms1, aes(x = Mix, y = logFC, fill = Mix)) + geom_boxplot() +
        geom_hline(yintercept = 0, linetype = "dashed", color = "grey50", size = .6) +
        geom_hline(yintercept = log2(2), linetype = "dashed", color = "grey50", size = .6) +
        geom_hline(yintercept = log2(3), linetype = "dashed", color = "grey50", size = .6) +
        geom_hline(yintercept = log2(4), linetype = "dashed", color = "grey50", size = .6) +
        geom_hline(yintercept = log2(5), linetype = "dashed", color = "grey50", size = .6) +
        facet_grid(cols=vars(Method)) +
        theme_prism() +
        scale_y_continuous(guide ="prism_offset_minor") +
        scale_fill_manual(values = myColors2) +
        theme(legend.position = "none") + 
        ylim(c(-4,4))

```


### DIA MS1 vs MS2 based quant for 1ng
```{r}
#Segment dataframe for marking expected ratios.
segment_df <- data.frame(x1 = log2(c(1, 2,3,4,5)), y1 = c(-2,-2,-1.3,-1.2,-1), y2 = c(2,2,1.3,1.2,1))


ggplot(data = ng1_fc_ms1, aes(x=logFC) ) +
  #geom_vline(xintercept = 0, linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(2), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(3), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(4), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(5), linetype = "dashed", color = "grey50", size = .8) +
   geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:1', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[1], color = myColors2[1], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:1', Method == "OTDIA"), 
            aes(y = ..density..), fill = myColors2[1], color = myColors2[1], alpha = 0.4) +

  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:2', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[2], color = myColors2[2], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:2', Method == "OTDIA"), 
            aes(y = ..density..), fill = myColors2[2], color = myColors2[2], alpha = 0.4) +
    
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:3', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[3], color = myColors2[3], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:3', Method == "OTDIA"), 
            aes(y = ..density..), fill = myColors2[3], color = myColors2[3], alpha = 0.4) +
  
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:4', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[4], color = myColors2[4], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:4', Method == "OTDIA"), 
            aes(y = ..density..), fill = myColors2[4], color = myColors2[4], alpha = 0.4) +
  
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:5', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[5], color = myColors2[5], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:5', Method == "OTDIA"), 
            aes(y = ..density..), fill = myColors2[5], color = myColors2[5], alpha = 0.4) +

  theme_prism() +
  geom_hline(yintercept = 0, size =1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey30", size = .5) +
  geom_hline(yintercept = -1, linetype = "dashed", color = "grey30", size = .5) +
  #geom_text(aes(x=5, y=-1, label="DIA MS1 quant"), color="black", angle = -90, size = 7) +
  #geom_text(aes(x=5, y=0.7, label="DIA MS2 quant"), color="black", angle = -90, size = 7) +
  xlim(c(-1.5,4.5)) + ylim(c(-2,2)) + xlab("log(H/L)") + ylab("Density") +
  geom_segment(aes(x=0, xend = 0, y = -2, yend = 1.8),linetype = "dashed", size = .8, color = myColors2[1]) +
  geom_segment(aes(x=1, xend = 1, y = -2, yend = 1.25),linetype = "dashed", size = .8, color = myColors2[2]) +
  geom_segment(aes(x=log2(3), xend = log2(3), y = -1.45, yend = .95),linetype = "dashed", size = .8, color = myColors2[3]) +
  geom_segment(aes(x=log2(4), xend = log2(4), y = -1.25, yend = .8),linetype = "dashed", size = .8, color = myColors2[4]) +
  geom_segment(aes(x=log2(5), xend = log2(5), y = -1.15, yend = .78),linetype = "dashed", size = .8, color = myColors2[5])


```

### DIA MS2 vs HRMS1 MS1 based quant for 1ng
```{r}

ggplot(data = ng1_fc_ms1, aes(x=logFC, fill = Mix, color = Mix) ) +
  #geom_vline(xintercept = 0, linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(2), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(3), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(4), linetype = "dashed", color = "grey50", size = .8) +
  #geom_vline(xintercept = log2(5), linetype = "dashed", color = "grey50", size = .8) +

   geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:1', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[1], color = myColors2[1], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:1', Method == "OTHRMS1"), 
            aes(y = ..density..), fill = myColors2[1], color = myColors2[1], alpha = 0.4) +

  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:2', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[2], color = myColors2[2], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:2', Method == "OTHRMS1"), 
            aes(y = ..density..), fill = myColors2[2], color = myColors2[2], alpha = 0.4) +
    
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:3', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[3], color = myColors2[3], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:3', Method == "OTHRMS1"), 
            aes(y = ..density..), fill = myColors2[3], color = myColors2[3], alpha = 0.4) +
  
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:4', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[4], color = myColors2[4], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:4', Method == "OTHRMS1"), 
            aes(y = ..density..), fill = myColors2[4], color = myColors2[4], alpha = 0.4) +
  
  geom_density(data = ng1_fc_ms2 %>% filter(Mix == '1:5', Method == "OTDIA"), 
            aes(y = -..density..), fill = myColors2[5], color = myColors2[5], alpha = 0.4) + 
  geom_density(data = ng1_fc_ms1 %>% filter(Mix == '1:5', Method == "OTHRMS1"), 
            aes(y = ..density..), fill = myColors2[5], color = myColors2[5], alpha = 0.4) +

  theme_prism() +
  geom_hline(yintercept = 0, size =1) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey30", size = .5) +
  geom_hline(yintercept = -1, linetype = "dashed", color = "grey30", size = .5) +
  #geom_text(aes(x=5, y=-1, label="DIA MS1 quant"), color="black", angle = -90, size = 7) +
  #geom_text(aes(x=5, y=0.7, label="DIA MS2 quant"), color="black", angle = -90, size = 7) +
  xlim(c(-1.5,4.5)) + ylim(c(-2,2)) + xlab("log(H/L)") + ylab("Density")  + 
  geom_segment(aes(x=0, xend = 0, y = 2, yend = -1.8),linetype = "dashed", size = .6, color = myColors2[1]) +
  geom_segment(aes(x=1, xend = 1, y = 1.8, yend = -1.25),linetype = "dashed", size = .6, color = myColors2[2]) +
  geom_segment(aes(x=log2(3), xend = log2(3), y = 1.35, yend = -.95),linetype = "dashed", size = .6, color = myColors2[3]) +
  geom_segment(aes(x=log2(4), xend = log2(4), y = 1.3, yend = -.8),linetype = "dashed", size = .6, color = myColors2[4]) +
  geom_segment(aes(x=log2(5), xend = log2(5), y = 1.2, yend = -.78),linetype = "dashed", size = .6, color = myColors2[5])

```