## Peptide quantification accuracy plots for DIA vs HRMS1-DIA (OT and LIT)

### Data and packages 

```{r}
library(tidyverse)
library(ggprism)
library(ggridges)
library(readxl)
```

```{r}
#Reading the LongReportV2 tables from SN16

min52 <- read.csv("data/SN17/R10_52min_Peptide.txt", sep = "\t") %>% as_tibble() %>% mutate(Gradient = "52min")
min29 <- read.csv("data/SN17/R10_29min_Peptide.txt", sep = "\t") %>% as_tibble() %>% mutate(Gradient = "29min")

```

#### Colors 
```{r}
myColors2 = c("#5f0f40", '#9a031e', '#fb8b24', '#e36414', '#0f4c5c')
myColors = c("#355070", '#6d597a', '#b56576', '#e56b6f', '#eaac8b')
```

### Data points per peak plots 
```{r}
#Points per peak plots 

ppp <- bind_rows(list(min52   %>% dplyr::select(R.Replicate, PEP.GroupingKey, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', Gradient),
                      min29  %>% dplyr::select(R.Replicate, PEP.GroupingKey, EG.DatapointsPerPeak, 'EG.DatapointsPerPeak..MS1.', Gradient))) %>% 
                      distinct() %>% select(-PEP.GroupingKey) # rule out duplicated peptides due to inclusion of proteins in the table

colnames(ppp) <- c("Rep", "MS2", "MS1", "Gradient")
```


#### Will redo this as ridge plots later on, for now it is good enough as a place holder 
```{r}
ggplot(ppp %>% filter(Rep == 1), aes(x = MS1, fill = Gradient, color = Gradient)) + 
        #geom_histogram(aes(y = ..density..)) +
        geom_density(alpha = 0.6) +
        facet_grid(rows=vars(Gradient), scales = "free") + 
        scale_fill_manual(values = myColors2) + 
        scale_color_manual(values = myColors2) +
        theme_prism() +
        theme(legend.position = "none") +
        xlim(c(0,25)) +
        ggtitle('MS1 Datapoints per peak')
```


```{r}
ggplot(ppp , aes(x = MS1, fill = Gradient, color = Gradient)) + 
        geom_histogram(aes(y = ..density..), binwidth = 1, alpha =0.7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(col=vars(Gradient)) + 
        geom_vline(xintercept = 3, linetype ="dashed", size = 0.7, color = "grey") + 
        scale_fill_manual(values = myColors2) + 
        scale_color_manual(values = myColors2) +
        theme_prism() +
        theme(legend.position = "none") +
        xlim(c(0,15)) +
        xlab('MS1 Datapoints per peak') + ylab("Density")

ggplot(ppp , aes(x = MS2, fill = Gradient, color = Gradient)) + 
        geom_histogram(aes(y = ..density..), binwidth = 1, alpha =0.7) +
        geom_density(alpha = 0.1,size = 1) +
        facet_grid(cols=vars(Gradient)) + 
        geom_vline(xintercept = 3, linetype ="dashed", size = 0.7, color = "grey") + 
        scale_fill_manual(values = myColors2[3:5]) + 
        scale_color_manual(values = myColors2[3:5]) +
        theme_prism() +
        theme(legend.position = "none") +
        xlim(c(0,15)) +
        xlab('MS1 Datapoints per peak') + ylab("Density")
```